webtalk_init -webtalk_dir C:/Users/Lorenzo/Desktop/project_1/project_1.sim/sim_1/impl/func/xsim/xsim.dir/project_tb_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep  1 01:45:41 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f074f3a-497c-4758-8ffb-81b79d1c2ba5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4010893f9b254a4c923bd47847eda118" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-8300 Eight-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3315 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5855017500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "79.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21172_KB" -context "xsim\\usage"
webtalk_transmit -clientid 537645526 -regid "" -xml C:/Users/Lorenzo/Desktop/project_1/project_1.sim/sim_1/impl/func/xsim/xsim.dir/project_tb_func_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Lorenzo/Desktop/project_1/project_1.sim/sim_1/impl/func/xsim/xsim.dir/project_tb_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Lorenzo/Desktop/project_1/project_1.sim/sim_1/impl/func/xsim/xsim.dir/project_tb_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
